using DarkTonic.CoreGameKit;

public class TriggeredSpawnerPlaymakerListener : TriggeredSpawnerListener
{
	public CGKPlaymakerUtility.PlaymakerEventSetting eventPropagatingSetting;
	public CGKPlaymakerUtility.PlaymakerEventSetting propagatedEventReceivedSetting;
	public CGKPlaymakerUtility.PlaymakerEventSetting waveEndedEarlySetting;
	public CGKPlaymakerUtility.PlaymakerEventSetting propagatedWaveEndedEarlySetting;
	public CGKPlaymakerUtility.PlaymakerEventSetting itemFailedToSpawnSetting;
	public CGKPlaymakerUtility.PlaymakerEventSetting itemSpawnedSetting;
	public CGKPlaymakerUtility.PlaymakerEventSetting waveFinishedSpawningSetting;
	public CGKPlaymakerUtility.PlaymakerEventSetting waveStartSetting;
	public CGKPlaymakerUtility.PlaymakerEventSetting waveRepeatSetting;
	public CGKPlaymakerUtility.PlaymakerEventSetting spawnerDespawningSetting;
	public CGKPlaymakerUtility.PlaymakerEventSetting customEventReceivedSetting;
}
